### PR TITLE
fix: `has_playlist` control disposition

### PR DESCRIPTION
**Pull request by christoph-heinrich**
I kept changes to a minimum for now, but there are a bunch of places that check for `state.playlist_count > 1` that could now be replaced with `state.has_playlist`.

Also there are a few places that use `mp.get_property_native('playlist-count')` instead of `state.playlist_count`. Is there a good reason for that or should those be replaced with the state property?

### CODE REVIEW

**Comment by tomasklaen** [comment]
> should those be replaced

Yeah, probably old leftovers from when the value was not in the state map.

**Comment by christoph-heinrich** [comment]
I was bothered by the fact that `state.has_playlist` is redundant with the existence of `state.playlist_count`, so I changed it.
In exchange the implementation of the check now has an `if`. Not sure which variant is preferable :neutral_face:

**Comment by tomasklaen** [comment]
No, I want the `has_playlist` back 😶.

**Comment by christoph-heinrich** [comment]
Ok, but I'll wait with that until your changes land. Then I can also replace all instances of `state.playlist_count > 1` with `state.has_playlist` without running into conflicts.

**Comment by tomasklaen** [comment]
Refactor now on main. I'm expecting tons of bugs in it 👼.

**Comment by christoph-heinrich** [comment]
Rebased, brought back `has_playlist` and all the `playlist-count` related changes applied.

**Pull request merged**
