### PR TITLE
fix: menu positioning issues

### PR DESCRIPTION
**Pull request by tomasklaen**
Did I miss anything?

### CODE REVIEW

**Comment by christoph-heinrich** [comment]
`math.max(math.min())` looks like `clamp()` to me.

I have never noticed before that the title/search bar is less tall then menu items, and as a consequence the top of the menu shifts slightly down when starting a search in a menu without title and a window small enough that the menu is scrollable. But the menu items stay at the same height, so the calculation is correct.

With the vertical padding not being a fraction of the available space anymore, we could use the same padding horizontally too.

Also this is somewhat nitpicky, but it's really more of a margin then padding.

**Comment by tomasklaen** [comment]
> I have never noticed before that the title/search bar is less tall then menu items

Hm... it shouldn't be, but I see it too. Probably forgetting to account for menu border, or item spacing somewhere.

> math.max(math.min()) looks like clamp() to me.

**Comment by christoph-heinrich** [comment]
> But I was thinking if we shouldn't just align menus statically to the top with space for title/search always reserved. That way we don't have to care for any shifts, or keep track of the top property on `search` table.
> 
> But when item with a submenu is all the way on the bottom, and submenu is short, its placing will look even weirder than it does now 😢.

That would certainly make things easier, but I'd expect the context menu being at the top to look weird.

**Comment by tomasklaen** [comment]
So I fixed the tiny shift, tweaked some stuff, and regarding the shifting of menu while searching, I've arrived at what I think is the best compromise here:

Since search starts, the menu's `top` position is only allowed to rise, never fall down, and goes back only after the search is canceled. This eliminates the top position jumping up and down as you search (issue in nested menus with `search_submenus` enabled), which was the main thing that bothered me.

**Comment by christoph-heinrich** [comment]
Works well, but one thing I've noticed during testing is that the width changes while typing in a `search_submenus` search.
It becomes wider then the original menu, which makes sense with the submenu concatenation, but as the search narrows the items down it becomes less wide again.

We could either keep track of the max width it had during a search and not let it get below that until the search is over, or we get the max width of all the items at search start and then keep it at that.

**Comment by tomasklaen** [comment]
I went with growing width as needed and not letting it shrink until search is canceled.

**Comment by christoph-heinrich** [comment]
One more thing, sorry for not realizing this sooner, but `options.menu_min_width*` should define the minimum size of the content, but if the window gets too small it should still be allowed to get smaller then that.

As a side-effect of that someone could, if they wanted to, set the minimum width to be really big so that the menu always takes up the full width of the window.

**Comment by christoph-heinrich** [comment]
This works.

```diff
diff --git a/scripts/uosc/elements/Menu.lua b/scripts/uosc/elements/Menu.lua
index 02e5a73..7bb8254 100644
--- a/scripts/uosc/elements/Menu.lua
+++ b/scripts/uosc/elements/Menu.lua
@@ -295,12 +295,14 @@ function Menu:update_dimensions()
 	-- This is a debt from an era where we had different cursor event handling,
 	-- and dumb titles with no search inputs. It could use a refactor.
 	local margin = round(self.item_height / 2)
-	local min_width = state.fullormaxed and options.menu_min_width_fullscreen or options.menu_min_width
+	local width_available = display.width - margin * 2
 	local height_available = display.height - margin * 2
+	local min_width = state.fullormaxed and options.menu_min_width_fullscreen or options.menu_min_width
+	min_width = math.min(min_width, width_available)
 
 	for _, menu in ipairs(self.all) do
 		local width = math.max(menu.search and menu.search.max_width or 0, menu.max_width)
-		menu.width = round(clamp(min_width, width, display.width - margin * 2))
+		menu.width = round(clamp(min_width, width, width_available))
 		local title_height = (menu.is_root and menu.title or menu.search) and self.scroll_step or 0
 		local max_height = height_available - title_height
 		local content_height = self.scroll_step * #menu.items
```

**Comment by christoph-heinrich** [comment]
This doesn't really matter because it's totally unusable at that size anyway, but since I noticed I might as well bring it up.
The clipping in the title could use some work.
image

**Pull request merged**
