### PR TITLE
fix: add border to title in top bar again

### LINKED ISSUE #158: Shadow of title is missing
image

### PR DESCRIPTION
**Pull request by christoph-heinrich**
The border got lost in 39ae0650c1eb3cad75043d71eeac2f0c4a46185d.

Closes #158

### CODE REVIEW

**Comment by tomasklaen** [comment]
I wanted it next to `border_color` 😶.

**Comment by christoph-heinrich** [comment]
I've moved it next to border_color. Can you reopen?

**Comment by tomasklaen** [comment]
I was in the middle of pushing my commits so I've just added it in the one that closed this.

**Comment by christoph-heinrich** [comment]
Totally missed the reference to that commit above your comment, sorry

**Pull request closed without merging**
