### PR TITLE
fix: translate audio channels and devices list

### PR DESCRIPTION
**Pull request by po5**
The channel count in track list couldn't be translated.
Also translate mpv's hardcoded entries in the audio devices list.

### CODE REVIEW

**Comment by natural-harmonia-gropius** [comment]
I will update `zh-hans` after this PR is merged.
Also, should the "No file" in title bar be translated?

**Comment by tomasklaen** [comment]
I've just pushed support for dynamic localization strings. It's just a cached lua `string.format()`, so if you rebase, you can swap this to:

```lua
device.description:sub(1, 7) == 'Default' and t('Default %s', device.description:sub(8)) or t(device.description)
```

and

```lua
t('%d channels', track['audio-channels'])
```

**Comment by po5** [comment]
Used `device.description:sub(9)`, 9 instead of 8, to prevent a double space, since `device.description` already has a space in it `Default (device name)`.
8 means having the translation string be `Default%s` to prevent the double space, looked uglier than `Default %s`.

**Comment by tomasklaen** [comment]
Whoops, missed that you're using `%d` in there. I guess just switch `%`s that are not `%s` in your other PR.

**Pull request merged**
