### PR TITLE
fix: integer resolution when scaling

### PR DESCRIPTION
**Pull request by christoph-heinrich**
The resolution passed to ass was not necessarily an integer while scaling, and I think that's what's caused the issues noted in #238. In my testing the thumbnail decoration renders nicely now with all sorts of fractional scaling factors.

@hooke007 Can you please test if this resolves your issues?

### CODE REVIEW

**Comment by hooke007** [comment]
Snipaste_2022-09-23_14-36-37

**Comment by hooke007** [comment]
hidpi: set 1.2 in system settings (But it was strange that mpv report it was 1.198)

current-window-scale : 0.789
Snipaste_2022-09-23_14-56-42

current-window-scale : 0.627
Snipaste_2022-09-23_15-00-18

current-window-scale : 0.754
Snipaste_2022-09-23_15-01-51

**Comment by tomasklaen** [comment]
Can I merge or are you still working on this?

**Comment by christoph-heinrich** [comment]
Still working on it. hooke's ability to find problems is truly astonishing.

**Comment by christoph-heinrich** [comment]
If you're looking for something to do, I noticed that playlist items now advance by 2 (so one gets skipped). Haven't had time to look into it or make a proper issue about it (with video).

**Comment by tomasklaen** [comment]
How are you advancing? Both letting mpv open the next item or doing `uosc/next` advances correctly to the next item.

**Comment by christoph-heinrich** [comment]
Simply letting it run out. I've noticed it happens only when I have speed >= 2. And I've also had it not happen once while speed was == 2.

https://user-images.githubusercontent.com/8932183/191990907-c18957e9-fe32-4f32-aff0-43ab1138d8c2.mp4

**Comment by tomasklaen** [comment]
Double jump, along with 2 other bugs this made me notice is fixed now 😭.

**Comment by christoph-heinrich** [comment]
Just noticed that depending on window size, despite border being a rectangle that stratches over the whole width, which is the same width that ass gets, it gets deteched from the window edge.
Screenshot_20220923_175238
Looks like libass really doesn't like rendering with scaled resolution. Arguably that's a bug in libass.

**Comment by christoph-heinrich** [comment]
After trying absolutely everything regarding scaling and rounding that I could think of, this is the best we can do. It's not great, far from perfect, but I hope it's good enough.

`math.ceil()` on the border because bigger sizes make the problem less noticeable, but it certainly still is noticeable unfortunately.

**Comment by hooke007** [comment]
Excellent now!

**Comment by christoph-heinrich** [comment]
Still excellent after the last change? because that got pushed only seconds before your comment, so not sure if you missed it or not.

**Comment by hooke007** [comment]
> Still excellent after the last change?

Yes

**Comment by tomasklaen** [comment]
Awesome!

**Pull request merged**
