### PR TITLE
fix: properly update title

### PR DESCRIPTION
**Pull request by christoph-heinrich**
Get the properties relevant to the title, observe and update based on their changes.

### CODE REVIEW

**Comment by christoph-heinrich** [comment]
osc.lua removes newlines and trailing slashes. Seems like a reasonable thing to do and while we're at it, we might as well trim whitespace.

**Comment by po5** [comment]
Property expansion can be nested, it's certainly an edge case that almost no one will run into but it exists. Have not checked if it works or not with your current code.  
Here's my lua parser with nesting support if it helps.  
https://github.com/ekisu/mpv-webm/blob/874d444ea5950d982ebb1b9babc17638991e7ed1/src/util.moon#L39-L80

**Comment by christoph-heinrich** [comment]
It already does recursive expansion :wink:

**Comment by dyphire** [comment]
In my test, I found an issue. When the following auto profiles are used, and the files stops playing and returns to the idle state, the wrong title will be displayed.
```ini
[idle-title]
profile-cond=idle_active
profile-restore=copy-equal
title=''

[uosc_filename]
profile-cond=not idle_active and path:match('://')==nil
profile-restore=copy
title=${filename}
```
image

This issue does not exist in the master branch.

**Comment by christoph-heinrich** [comment]
> In my test, I found an issue. When the following auto profiles are used, and the files stops playing and returns to the idle state, the wrong title will be displayed.

I've tried `mpv --keep-open=no --idle=yes` with your auto profiles, dragging in files and letting them run out to return to idle. Works without any problems  for me.

**Comment by dyphire** [comment]
> I've tried `mpv --keep-open=no --idle=yes` with your auto profiles, dragging in files and letting them run out to return to idle. Works without any problems for me.

yes, The latest push fixes it.

**Comment by christoph-heinrich** [comment]
Ah ok, it didn't handle the case where no properties are need for the title, thus no update happened.

**Comment by dyphire** [comment]
> Ah ok, it didn't handle the case where no properties are need for the title, thus no update happened.

I can't reproduce it anyway again, just fine.

**Comment by christoph-heinrich** [comment]
> a closing brace will close every open brace

the default title is `${?media-title:${media-title}}${!media-title:No file}` which does have two successive closing braces. if the first one closed both scopes, we'd always have a "}" in our titles, but we don't.

**Pull request merged**
