### PR TITLE
fix: shifting of digits due to non monospace font

### PR DESCRIPTION
**Pull request by christoph-heinrich**
Why draw the whole string at once when you can draw each symbol individually two times!

Not sure about this but it does solve the shifting digits mentioned in the comment.

~~Would be nice to also use this in the time tooltip, but I don't see an easy way of doing that.~~

Ref. https://github.com/tomasklaen/uosc/issues/722#issuecomment-1783866244

### CODE REVIEW

**Comment by po5** [comment]
libass supports some generic font families that ["map to sensible platform-specific font families"](https://github.com/libass/libass/blob/e64390522d9501a2c7e6a51c31a5b2a1f3a35cd1/libass/ass_fontselect.h#L115-L131), if we don't care about respecting the user's osd-font for timestamps: `sans-serif`, `serif`, `monospace`

**Comment by christoph-heinrich** [comment]
Yes but as I pointed out [here](https://github.com/tomasklaen/uosc/issues/722#issuecomment-1783880134), I don't like how it looks.

monospace
image
this hack
image

**Comment by dyphire** [comment]
LGTM

**Comment by christoph-heinrich** [comment]
I thought of a way to use it in the tooltip, but the code is kinda ugly...

**Comment by tomasklaen** [comment]
I don't know about this one. I'm concerned about the performance. That's a lot more ass tags this is pushing. Could you do a benchmark and report the difference between lets say drawing a hundred timestamps with `:txt()` and the same with `:timestamp()`?

I know there's a limit of ass tags after which libass can't keep up and UI starts stuttering, and the amount of ass tags this adds just doesn't feel like it's worth it.

**Comment by christoph-heinrich** [comment]
I was also worried about the performance impact at first, but it works fine on a 10 year old machine locked to it's lowest frequency, so it's probably fine???

100 `:timestamp()` takes 10.3 ms
100 `:txt()` takes 2.1 ms

So yeah pretty big difference, but we're not actually drawing that many of them.

When hovering the timeline so that three timestamps are drawn the times are:
`:timestamp()` takes 810 us
`:txt()` takes 290 us

That's a big difference relatively speaking, but for some more context, leaving the timeline so that the controls are shown drives the `:txt()` time up to 570 us, and that is with not that many of them.
image

So it should be fine, as long as we're not drawing the timestamps of chapters in the chapter menu with them.

**Comment by tomasklaen** [comment]
This makes me feel like adding a toilet paper roll asset made of 1M polys into a game. To remedy a problem that affects <1% people.

I would hate knowing that timestamps are this inefficient for 99% that absolutely don't need it, but I wouldn't mind merging this if we only used `:timestampt()` when `time_precision > 0`.

**Comment by christoph-heinrich** [comment]
It is also a problem with `time_precision=0` but less noticeable. I already noticed it months ago without increased precision, but I suspected it might not be a problem with other fonts (didn't test) and it's not that noticeable.

image
image

As you can see the `11` takes up a little bit less space, thus shifting the rest to the right (opening the images in tabs and switching between them makes it easier to see).

But I'm also somewhat bothered by the additional performance impact, so there you go :)

**Comment by christoph-heinrich** [comment]
I've tested other fonts now (should have done that much sooner) and the only ones that have that problem for me are the Liberation variants (except mono), so I guess we could say "don't use a shitty font" and be done with it.

**Comment by FichteFoll** [comment]
If performance is still a concern, you could probably speed it up a little by caching the results of [this block](https://github.com/tomasklaen/uosc/commit/6cbf0731f3ce24df215e44e67da6c4d16d64eed5#diff-f313b2b2f9768dd7521bbd9b5474aba8c8205f5481b13dae735f6cd9b7a29c55R122-R128) (for the same font, which I'm not sure whether it is configurable dynamically).

**Comment by christoph-heinrich** [comment]
Lua performance isn't the problem here :wink: it's about the speed of libass.

**Comment by FichteFoll** [comment]
I was thinking of the `text_width` calls primarily, but it seems that is already cached, so you can disregard my comment.

**Pull request merged**
