### PR TITLE
feat: reintroduce lines chapter style

### PR DESCRIPTION
**Pull request by po5**
It had been removed in 3c85721f1ad24d030ff3f0a437aa6d5a254ff779 in favor of diamonds, for readability reasons with the introduction of uncached ranges.  
I never liked them, even if the chapter snapping feature is nice.

Overview of this new implementation of line chapters:
- Customizable chapter width
- Close-by chapters cannot produce ugly double-opacity overlaps
- Styles for full line, top, bottom, and a new option for middle (it came free with the implementation)
- Plays nice with cached ranges

Disregard the thumbnail spam, if it wasn't obvious that it's unrelated.  

I'm Embarrassed For Her _watch?v=COALkXIzN3E_000558 658

We no longer invert cached ranges.  
I've removed some of the cached ranges mangling (merging nearby ranges, skipping short ranges), it will have to be redone.  
Cached ranges no longer rely on tricky positioning based on font size. The texture is guaranteed to be continuous.

### CODE REVIEW

**Comment by po5** [comment]
Haven't shuffled code around to keep the diff readable, I know indentation is wrong inside newly added conditions.

The idea used in both of these commits is to render the entire bar in a single ASS event, and \clip out areas to keep.  
This avoids any unintentional overlaps.

**Comment by christoph-heinrich** [comment]
I must be missing something here, as I've never worked with the scaled clipping before.
In the generation of `chapters_clip` you use regular coordinates, but then when inserting that text into clip a scale of 4 (factor 8) is specified. How come the coordinates don't need to be scaled 8x for that?

**Comment by po5** [comment]
mpv uses scale 4 by default for drawings:
https://github.com/mpv-player/mpv/blob/94c414bd1cf8744ab979373e29d3c40aed15b86b/player/lua/assdraw.lua#L5-L7
https://github.com/mpv-player/mpv/blob/94c414bd1cf8744ab979373e29d3c40aed15b86b/player/lua/assdraw.lua#L16-L18

**Comment by christoph-heinrich** [comment]
I had no idea those coordinates get scaled and made in to integers internally by the `coord()` function instead of having a decimal in the text :laughing: 
Just goes to show how little I actually know about that. Thanks for the pointer.

**Comment by po5** [comment]
Doesn't play nice with `window_border_size`, wait before merging.

**Comment by christoph-heinrich** [comment]
Would be great if that could also support the chapter snapping, there wouldn't be any downside to it with any of the chapter styles except for `lines`.

**Comment by po5** [comment]
Can someone take a look? It now works with `window_border_size`, and I reintroduced cached ranges filtering.
I want to make sure the filtering is still correct now that it's no longer inverted, and also check that `buffered_playtime` logic is correct.
It took me a while to figure out that `ass_mt:texture` is *supposed* to overextend, lot of time wasted trying to figure out positioning when it's expected to get clipped out.

I will try to implement chapter snapping.

**Comment by natural-harmonia-gropius** [comment]
Don't show indicator that time <= 1 and make lines thinner would looks better.

image
image

**Comment by po5** [comment]
> Don't show indicator that time <= 1

Unrelated to this PR, diamond style chapters also show up.

> make lines thinner

Old default was 6, if anything it should be changed to match. https://github.com/tomasklaen/uosc/pull/119#issuecomment-1221527976
https://github.com/tomasklaen/uosc/blob/852b724b6acfa95795af124c87054f66f2b60cc8/scripts/uosc.lua#L160

**Comment by po5** [comment]
> This is more code to maintain

Changes are small and confined enough that you shouldn't need to even think about the chapter lines code when touching other code.

> you can't click to snap to chapter anymore, and there's no way to add it back, because it'd mean removing ability to seek around the chapter

There are line modes that don't take up the entire timeline height, e.g. `lines-top`, which can act just like diamonds where a tiny portion at the top of the timeline is obscured by snapping.

Extra modes all share the same code, but if you would rather only have `lines-top` I don't care much about getting this merged, I think `lines` looks better and it's what I would use myself.

Maybe it's the diamond shape I find off-putting, so I tried removing `ass:line_to(chapter_x, chapter_y - radius)` to turn it into a triangle.
It wasn't enough so I tried setting `chapter_y` to `fay`, set `\bord0`.
The current chapter style doesn't fit the style of the rest of uosc's flat elements, it feels like it's tacked on top.
Even with these changes it's not enough, because it's still trying to tack another layer of color onto the timeline.
In my mind it should feel like a divot, not a floating icon.

Twin Peaks S01E01 Pilot 720p BluRay DD5 1 x264-DON mkv_003103 695

A-B loop indicators have the same issue, they look like they don't belong. I'm not sure how to fix it completely.
We could \clip out chapter triangles from the two sides of timeline_style=bar, which would allow us to maintain two consistent colors within the timeline.
I don't see what could be done for A-B loop.

I will submit cached ranges updates as a separate PR, feel free to close this if you're against line chapters but I'd like to hear your view on the issue of floating elements that imo don't belong on the flat timeline.

**Comment by christoph-heinrich** [comment]
The notches are an interesting idea and would fit in with the volume bar, but how would that work with a minimized timeline?

**Comment by dyphire** [comment]
> Maybe it's the diamond shape I find off-putting, so I tried removing `ass:line_to(chapter_x, chapter_y - radius)` to turn it into a triangle.

I prefer diamond style chapters because they are more beautiful. I have never liked chapters with line styles, as they appear chaotic and lack aesthetic appeal. But this is a personal preference difference, and I don't object to this PR.

**Comment by tomasklaen** [comment]
> Changes are small and confined enough

The amount of code is not that big of an issue, it's that every time we need to touch timeline it's one more thing that needs to be tweaked (or potentially 4 in this case). Also, if we ever need to add some new indicator to timeline, it's surely going to clash with some of the chapter indicators, so I'll either have to design around it somehow (unlikely), or remove the indicator and cause a major bump.

> The current chapter style doesn't fit the style of the rest of uosc's flat elements.

We'd have to agree to disagree here, I think they look good, and I wouldn't expect uosc's design to be limited to rectangles only.

> A-B loop indicators have the same issue, they look like they don't belong.

I don't share this view either, but if you only expect rectangles than no other shape will belong I guess. Overall, having different indicators use different shapes helps people differentiate between them.

But thanks for remind me of a-b loop - here's an indicator that already clashes with lines.

> _screenshot_

I wouldn't mind this triangle alternative. It could be implemented by simply skipping drawing the top point of the diamond, and enabled with `timeline_chapters_compact=yes/no` option (or `_discrete` maybe?).

The indicator should revert to normal full diamond rendering when it's hovered.

But I do consider this an unnecessary change just to appease your particular hatred of diamonds :)

**Comment by po5** [comment]
Doubt this is getting merged or implemented in any capacity, see https://github.com/tomasklaen/uosc/issues/550#issuecomment-1752004918.

**Pull request closed without merging**
