### PR TITLE
Add Ukrainian UI lang

### PR DESCRIPTION
**Pull request by ke1ne**
Add Ukrainian UI lang

### CODE REVIEW

**Comment by po5** [comment]
Thanks, doubt the 2nd commit will get merged though (:

**Comment by zakiph27** [comment]
While it's understandable that you may feel anger and frustration due to the conflict between Russia and Ukraine, promoting the deletion of an entire language translation or banning an entire group of people is not an appropriate solution. It's essential to remember that the actions of governments and political leaders do not represent the beliefs and attitudes of every individual within a nation.

**Comment by ke1ne** [comment]
> Thanks, doubt the 2nd commit will get merged though (:

Actually, I wanted to separate them, but did some mistake because of lack pull request experience.

**Comment by ke1ne** [comment]
> While it's understandable that you may feel anger and frustration due to the conflict between Russia and Ukraine, promoting the deletion of an entire language translation or banning an entire group of people is not an appropriate solution. It's essential to remember that the actions of governments and political leaders do not represent the beliefs and attitudes of every individual within a nation.

It's not about "anger and frustration". While there is no active anti-war movement of Russians, it's fully fair to accept this as a genocide support. And it's not a "conflict", it's aggressive invasion and a war crime.

**Comment by christoph-heinrich** [comment]
> genocide

I'm pretty sure their intention is not the destruction of Ukrainians as a people, making it not a genocide.

Also there are plenty of Ukrainians that primarily speak Russian, which makes this translation no only useful for citizens of the Russian state.

**Comment by dyphire** [comment]
I think we should also remove English support. "English is an inherently racist language to begin with. It's the language of the conquerors, invaders, and slave owners. Keep in mind that this is the language the people kidnapped from Africa had to learn - to understand the commands of their owners. The whole reason English is a lingua franca is because of the brutal history of anglo colonialism. And the language is inseparable from this culture."

**Comment by christoph-heinrich** [comment]
> I think we should also remove English support. <because racism>

Agree. The same also goes for all other languages because historically every group of people has enslaved some other people at some point. Let's translate the project into [Lojban](https://en.wikipedia.org/wiki/Lojban), because no slave owners spoke that language, nor has any native speaker ever started a war (or done anything else for that matter). /s

**Comment by tomasklaen** [comment]
Yeah, I'm not going to merge this with the ru deletion.

**Comment by christoph-heinrich** [comment]
We could cherry-pick 483bc8547e9e9a1d21f75ab233b5e6200397d9bc

**Comment by tomasklaen** [comment]
I don't think author would like that without us also deleting RU.

**Comment by christoph-heinrich** [comment]
Oh look at that [GPL-3.0 project](https://github.com/ke1ne/uosc/tree/main) that just happens to have a ukranian translation file compatible with this project... :wink:

**Comment by ke1ne** [comment]
The first goal of separate commits was to discuss more softly. But the accident case cleared the situation even better.

This hypocritical westsplaining storm is ridiculous. Do your homework.

https://www.hmd.org.uk/learn-about-the-holocaust-and-genocides/what-is-genocide/the-ten-stages-of-genocide/
https://newlinesinstitute.org/genocide/the-russian-federations-escalating-commission-of-genocide-in-ukraine-a-legal-analysis/
https://www.atlanticcouncil.org/blogs/ukrainealert/new-report-highlights-evidence-of-escalating-russian-genocide-in-ukraine/
https://twitter.com/tweet4anna/status/1636742919431356417

**Comment by christoph-heinrich** [comment]
That's hilarious :rofl:
At first I wasn't sure about the moral implications of cherry-picking that commit (legally it's totally fine), but now I'm all for it.

dyphire is actually Chinese, so much for your "westsplaining storm".

"Here is an explanation of genocide"
Brought to you by the same people that call everything they don't like right-wing extremism.

Here are some actual dictionaries for Mr. "do your homework":
https://www.merriam-webster.com/dictionary/genocide
https://dictionary.cambridge.org/dictionary/english/genocide
https://www.oxfordlearnersdictionaries.com/definition/english/genocide
Notice something they all have in common? It's about intentionally destroying a group of people, something that is not the case in that war.

**Comment by ke1ne** [comment]
> It's about intentionally destroying a group of people

This is exact case of this war.

**Pull request closed without merging**
