### PR TITLE
feat: add multi-subtitles as filters

### PR DESCRIPTION
**Pull request by MasouShizuka**
feat:
multi-subtitles: select from current directory or mkv built-in subtitles and load them as filters
playlist-prev-keep-multi-subtitles-status: select the previous episode and update the subtitles of the corresponding video
playlist-next-keep-multi-subtitles-status: select the next episode and update the subtitles of the corresponding video

### CODE REVIEW

**Comment by tomasklaen** [comment]
What is this doing? 😨 From reading it for like 5 minutes I think it's trying to select same subtitles when navigating to the next file? But it's doing something with filters, and files? and ... I'm not sure.

**Comment by MasouShizuka** [comment]
For example, the video directory is like:
```
video 01.mkv
video 01_sc.ass
video 01_tc.ass
video 02.mkv
video 02_sc.ass
video 02_tc.ass
```

When playing the `video 01.mkv`, you can load `video 01_sc.ass` and load `video 01_tc.ass` as filter using `multi-subtitles` menu.
And by `playlist-next-keep-multi-subtitles-status`, `video 02.mkv` will load `video 02_tc.ass` as filter.

**Comment by po5** [comment]
Is this a way to load a secondary subtitle but keep its styling? This would be more suited as its own script.

**Comment by MasouShizuka** [comment]
If you use filter to load sub, it will keep the style.

**Comment by hooke007** [comment]
There is no doubt it should be standalone.

**Comment by tomasklaen** [comment]
Yeah you should make this as your own script. You can use uosc's [`open-menu` message API](https://github.com/tomasklaen/uosc#open-menu-menu_json-submenu_id) if you want to use uosc's menus.

**Pull request closed without merging**
