### PR TITLE
fix: use mouse-pos property instead of keybinds

### LINKED ISSUE #295: Mouse drag not propagated to other scripts
I did not study the code much but it seems mouse drag is being swallowed even if no action is bound to it in the given context/situation.

E.g. I would like `uosc` to work with `MBTN_LEFT  script-binding drag-to-pan
` in `input.conf` (drag-to-pan comes from https://github.com/occivink/mpv-image-viewer/blob/master/scripts/image-positioning.lua script). But the binding works only if I do not put `uosc` into `scripts/` folder.

Any hints how to propagate the binding instead of swallowing it?

### PR DESCRIPTION
**Pull request by christoph-heinrich**
Closes #295

### CODE REVIEW

**Comment by hooke007** [comment]
LGTM

**Comment by christoph-heinrich** [comment]
Cleaned it up a bit.

**Comment by tomasklaen** [comment]
Yup, looks good, just refactor away the `local mouse_keybinds = {}`, as we don't need it anymore.

Also while I'm looking at it, is there an observable property with window position? Because current `pause_on_click_shorter_than` implemented in there cancels the click only after the configured time. It'd be cool if it also canceled on any window movement, because currently if person drags and releases the window still within the configured time, the click (pause) happens, and it shouldn't. I didn't implement it as I couldn't find how to tap into window position in the docs. But maybe someone else knows about something?

**Comment by christoph-heinrich** [comment]
`mouse-pos/hover` becomes false when dragging the window, so we can certainly do something with that.

**Comment by hooke007** [comment]
I was confused about `pause_on_click_shorter_than`. If user's `MBTN_LEFT` is bound to another command such as `cycle mute` , they could not activate the command they want.

**Comment by tomasklaen** [comment]
Well yeah, you can't have more than one function per button. That's to be expected, no? You'd want it to drag, pause AND do what's defined in `input.conf`?

**Comment by hooke007** [comment]
The first time I used uosc, it took me a long time ti figure out why my MBTN_LEFT doesn't work...
There is no related content mentioned in the doc. My idea is making that command configurable.
```lua
local click_timer = mp.add_timeout(duration_seconds, function() mp.command(options.usr_command) end)
```

**Comment by Natural-Harmonia-Gropius** [comment]
I think this function could be separated into another script, as this behavior also becomes sluggish when uosc is under high load.

**Comment by christoph-heinrich** [comment]
Getting that to work correctly is hard because pressing the left mouse button triggers down and up events.
@Natural-Harmonia-Gropius will you make it work right? because then I'll stop tinkering with it.

**Comment by christoph-heinrich** [comment]
I've made it work correctly now.

**Comment by Natural-Harmonia-Gropius** [comment]
Here's a funny issue, just keep it before any real improvement. 🫠
https://github.com/tomasklaen/uosc/pull/301#issuecomment-1271809454

**Comment by tomasklaen** [comment]
If I click without moving the mouse nothing happens.

**Comment by christoph-heinrich** [comment]
While working on https://github.com/mpv-player/mpv/issues/10723#issuecomment-1271882790 I realized that it behaves differently in windows mode then in fullscreen/maximized, so I'll have to adjust it.

Or just drop the last commit, remove that "short click to pause" and use whatever @Natural-Harmonia-Gropius makes instead.

**Comment by Natural-Harmonia-Gropius** [comment]
Mine is trying to be a replacement for input.conf, it won't be available so fast.
At least I think the uosc function works correctly now, so just keep it and make sure the code is not aggressive when the function is turned off.

**Comment by christoph-heinrich** [comment]
Should work now both in windowed and non windowed mode.

**Comment by tomasklaen** [comment]
This doesn't filter drags?

**Comment by christoph-heinrich** [comment]
No, short drags get recognized as short clicks, and I don't see a way of filtering that out.

**Pull request merged**
