### PR TITLE
bugfix on windows, scoop

### LINKED ISSUE #409: doesn't work on windows with scoop
On Windows, when using mpv and lua installed via scoop.sh `scoop install lua mpv-git`, uosc errors with this:

```cmd
[uosc]
[uosc] stack traceback:
[uosc]  [C]: in function 'require'
[uosc]  ...op/apps/mpv-git/current/portable_config/scripts/uosc.lua:15: in main chunk
[uosc]  [C]: at 0x7ff619a3a5c0
[uosc]  [C]: at 0x7ff619a38ca0
[uosc] Lua error: error loading module 'uosc_shared/lib/std' from file 'D:\Software\Scoop\apps\lua\current':
[uosc]  cannot read D:\Software\Scoop\apps\lua\current: Invalid argument
```

<details><summary>Expand for version and installation details</summary>

```
$ mpv --version
mpv 0.35.0-62-gcb15bc4324 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Sun Dec 25 12:22:28 2022
libplacebo version: v5.229.1-49-g22ce304
FFmpeg version: git-2022-12-24-f8a2a6507
FFmpeg library versions:
   libavutil       57.43.100
   libavcodec      59.55.103
   libavformat     59.34.102
   libswscale      6.8.112
   libavfilter     8.53.100
   libswresample   4.9.100
```
uosc version:
```lua
--[[ uosc 4.5.0 - 2022-Dec-07 | https://github.com/tomasklaen/uosc ]]
local uosc_version = '4.5.0'
...
```
```
$ lua -v
Lua 5.4.2  Copyright (C) 1994-2020 Lua.org, PUC-Rio
```
```pwsh
$ scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15
```
scoop environment (installation directory)
```
$ echo %SCOOP%
D:\Software\Scoop
```
</details>

### PR DESCRIPTION
**Pull request by phanirithvij**
fixes #409

With this fix applied, I can confirm the error that I've mentioned in the issue is gone and uosc works perfectly.

### CODE REVIEW

**Comment by tomasklaen** [comment]
Thx for spending the time figuring it out, but it might be unnecessary. For the next version (when current PRs are resolved) I plan on dropping support for mpv <=0.32, which means we will be able to restructure the script into a single `uosc` folder and make the current `package.path` hack not needed anymore, so this should just work.

**Comment by hooke007** [comment]
The question is ... why you are trying to use lua 5.4
So far mpv would never support any version over 5.3

**Comment by phanirithvij** [comment]
Oh, I didn't know that because I must've been using Lua 5.4 with mpv for a few years (as I installed them together with scoop) and I didn't encounter any issues with Lua scripts until now.
And as I said the whole script (the osc) works after this minor fix and I assume this fix is backward compatible with Lua 5.2.

**Comment by hooke007** [comment]
Havn't met any wrong here.

**Pull request closed without merging**
