### PR TITLE
doc: add windows commands

### PR DESCRIPTION
**Pull request by unavailable500**
Hi,
just added equivalent commands for windows to install the project.
Let me know if it's ok.
Regards

### CODE REVIEW

**Comment by tomasklaen** [comment]
I don't think thumbfast installation belongs here. It's awesome and recommended, but still a separate project with optional integration in uosc, it shouldn't be a mandatory part of uosc installation.

**Comment by unavailable500** [comment]
That's the same logic that you found in the Linux installation in the line 51th. 
`wget -NP ~/.config/mpv/scripts/ https://raw.githubusercontent.com/po5/thumbfast/master/thumbfast.lua`

If you want I can remove that. Do you want that I remove that also for the Linux installation script?

**Comment by tomasklaen** [comment]
I guess I merged it without noticing :)

Well, since it has been there all this time, any other inputs on this? Should we include thumbfast in these installation commands/scripts?

**Comment by tomasklaen** [comment]
Here's where I'm coming from:

First, I use uosc on multiple machines, but don't need thumbfast on all of them. So I feel weird about having it be forced, because I'd have to remove it manually afterwards.

Second, I think thumbfast is going through a redesign atm that might split it into multiple files. And ther emight be further changes in the future. This means we now have to maintain an installation code for a disconnected 3rd party script, which in turn means there now are external factors that can break this, and it will remain broken until someone notices and decides to create an issue.

**Comment by christoph-heinrich** [comment]
I don't think it should be part of the installation instructions.
Mentioning as an optional script that pairs well with uosc (as is already done) is enough.

**Comment by unavailable500** [comment]
Done! Yes I also think it's better since thumbfast installation process could change in the future

**Comment by unavailable500** [comment]
> Why is it `APPDATA` only?

What do you mean?
That's where the config file goes on windows: https://mpv.io/manual/stable/
> You can find the exact path by running echo %APPDATA%\mpv\mpv.conf in cmd.exe.

**Comment by hooke007** [comment]
I cannot say all here but the win users I know most use `portable_config` only.

**Comment by tomasklaen** [comment]
I use `portable_config` as well, but according to mpv docs (https://mpv.io/manual/stable/#files-on-windows) `%APPDATA%/mpv` is the primary/main intended place for mpv to read the config from, so I think this is appropriate. Everyone else can extract to their portable config folders.

**Pull request merged**
